---
  - name: configure provider
    set_fact:
      provider:
        username: "{{ vault_user }}"
        password: "{{ vault_password }}"
        auth_pass: "{{ vault_enable }}"
        host: "{{ ansible_host }}"
        authorize: yes

  - name: Setup hostname
    ios_config:
        provider: "{{ provider }}"
        lines:
          - hostname {{ inventory_hostname }}

  - name: Enable snmp
    ios_config:
        provider: "{{ provider }}"
        lines:
          - snmp-server community {{ snmp_ro_string }} RO

  - name: Disable vtp 
    ios_config:
      provider: "{{ provider }}"
      lines:
        - vtp mode off

  - name: Setup vlans
    ios_config:
        provider: "{{ provider }}"
        lines:
          - name {{ item.value.description}}
        parents:  vlan {{ item.value.number }}
    with_dict: "{{ vlans }}"

  - name: Setup mgmnt VLAN Interface
    ios_config:
      provider: "{{ provider }}"
      lines:
        - description mgmnt vlan
        - ip address {{ ansible_host }} 255.255.255.0
      parents: interface vlan 1
  
